[package]
name = "kos-stub"
version = "0.1.1"
authors = ["Denys Bezmenov <denys@kscale.dev>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/kscalelabs/kos"
description = "Stub KOS platform"

[dependencies]
kos_core = { version = "0.1.1", path = "../../kos_core" }
async-trait = "0.1"
eyre = "0.6"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
prost-types = "0.13"
prost = "0.13"
tracing = "0.1"