[package]
name = "stub"
version = "0.1.0"
edition = "2021"

[dependencies]
kos_core = { path = "../../kos_core" }
async-trait = "0.1"
eyre = "0.6"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
prost-types = "0.13"
prost = "0.13"
tracing = "0.1"