[workspace]

members = [
    "kbrain/bindings",
    "kbrain/rust",
]
resolver = "2"

[workspace.package]

version = "0.1.0"
authors = ["Wesley Maa <wesley@kscale.dev>", "Pawel Budzianowski <pawel@kscale.dev>", "Benjamin Bolte <ben@kscale.dev>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/kscalelabs/kbrain"
description = "The brain for K-Scale's humanoid robots"
documentation = "https://docs.kscale.dev/software/actuators/overview"
readme = "README.md"
