[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
kscale_micro = { path = "../platforms/kscale_micro", optional = true }
kscale_pro = { path = "../platforms/kscale_pro", optional = true }

# Also can add external platforms here?
# e.g. third_party_platform = { git = "https://github.com/thirdparty/platform", optional = true }

# Common dependencies
[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.6", features = ["transport"] }

[features]
kscale_micro = ["kscale_micro"]
kscale_pro = ["kscale_pro"]
default = []