[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
kos_core = { path = "../kos_core" }
kscale_micro = { path = "../platforms/kscale_micro", optional = true }
kscale_pro = { path = "../platforms/kscale_pro", optional = true }
sim = { path = "../platforms/sim", optional = true }
stub = { path = "../platforms/stub", optional = true }

tokio = { version = "1", features = ["full"] }
tonic = { version = "0.12", features = ["transport"] }
eyre = "0.6"
tracing = "0.1"
tracing-subscriber = "0.3"
tower = "0.5"
tower-http = {version = "0.6", features = ["cors"]}
tonic-web = "0.12"


# Also can add external platforms here?
# e.g. third_party_platform = { git = "https://github.com/thirdparty/platform", optional = true }

[features]
kscale_micro = ["dep:kscale_micro"]
kscale_pro = ["dep:kscale_pro"]
sim = ["dep:sim"]
stub = ["dep:stub"]
default = ["stub"]
