[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
kscale_micro = { path = "../platforms/kscale_micro", optional = true }
kscale_pro = { path = "../platforms/kscale_pro", optional = true }

tokio = { version = "1", features = ["full"] }
tonic = { version = "0.12", features = ["transport"] }

# Also can add external platforms here?
# e.g. third_party_platform = { git = "https://github.com/thirdparty/platform", optional = true }

[features]
kscale_micro = ["dep:kscale_micro"]
kscale_pro = ["dep:kscale_pro"]
default = []