limbs:
  LeftArm:
    port_name: /dev/ttyCH341USB0
    motor_configs:
      1:
        motor_type: TYPE03
        kp: 50.0
        kd: 1.0
      2:
        motor_type: TYPE03
        kp: 50.0
        kd: 1.0
      3:
        motor_type: TYPE02
        kp: 50.0
        kd: 1.0
      4:
        motor_type: TYPE02
        kp: 50.0
        kd: 1.0
      5:
        motor_type: TYPE01
        kp: 50.0
        kd: 1.0
  RightArm:
    port_name: /dev/ttyCH341USB0
    motor_configs:
      1:
        motor_type: TYPE03
        kp: 50.0
        kd: 1.0
      2:
        motor_type: TYPE03
        kp: 50.0
        kd: 1.0
      3:
        motor_type: TYPE02
        kp: 50.0
        kd: 1.0
      4:
        motor_type: TYPE02
        kp: 50.0
        kd: 1.0
      5:
        motor_type: TYPE01
        kp: 50.0
        kd: 1.0
