[package]
name = "kos-kbot"
version = "0.1.1"
authors = ["Wesley Maa <wesley@kscale.dev>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/kscalelabs/kos"
description = "KOS platform for KBot"

[dependencies]
kos_core = { version = "0.1.1", path = "../../kos_core" }
eyre = "0.6"
krec = "0.2"
tracing = "0.1"
async-trait = "0.1"
robstridev2 = "0.3"
gstreamer = "0.20"
gstreamer-app = "0.20"
gstreamer-video = "0.20"
uuid = "1"
tokio = { version = "1", features = ["full"] }
[target.'cfg(target_os = "linux")'.dependencies]
imu = ">=0.1.6"
chrono = "0.4"
