[package]
name = "kos-kbot"
version = "0.1.1"
authors = ["Wesley Maa <wesley@kscale.dev>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/kscalelabs/kos"
description = "KOS platform for KBot"

[dependencies]
kos_core = { version = "0.1.1", path = "../../kos_core" }
eyre = "0.6"
tracing = "0.1"
async-trait = "0.1"
robstride = "0.2.8"

[target.'cfg(target_os = "linux")'.dependencies]
imu = "0.1.4"
