[package]
name = "kos-zeroth-01"
version = "0.1.1"
authors = ["Denys Bezmenov <denys@kscale.dev>", "Jingxiang Mo <jx@kscale.dev>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/kscalelabs/kos"

[dependencies]
kos_core = { version = "0.1.1", path = "../../kos_core" }
async-trait = "0.1"
eyre = "0.6"
